name: tonos_de_pared
description: "Comparador de Tonos de Pared"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+4
  english_words: ^4.0.0
  provider: ^6.0.0
  dropdown_button2: ^2.3.8
  flutter_colorpicker: ^1.1.0
  http: ^1.2.2
  image: ^3.0.1
  shared_preferences: ^2.1.1
  permission_handler: 11.3.1
  flutter_lints: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_background: "assets/logo.png"



flutter:
  uses-material-design: true
  assets:
    - assets/
